### ISSUE TITLE
Invalid HTTP method: PATCH

### ISSUE THREAD

**Issue by andre77** [mmazi/rescu#147]
Facing a problem, where a REST API has a "PATCH" method
using the jakarta.ws.rs.PATCH annotation i can very well setup such a call, but it fails with
```
Exception in thread "main" java.net.ProtocolException: Invalid HTTP method: PATCH
	at java.base/java.net.HttpURLConnection.setRequestMethod(HttpURLConnection.java:491)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.setRequestMethod(HttpURLConnection.java:598)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.setRequestMethod(HttpsURLConnectionImpl.java:343)
	at si.mazi.rescu.HttpTemplate.configureURLConnection(HttpTemplate.java:182)
	at si.mazi.rescu.HttpTemplate.send(HttpTemplate.java:123)
	at si.mazi.rescu.RestInvocationHandler.invokeHttp(RestInvocationHandler.java:152)
	at si.mazi.rescu.RestInvocationHandler.invoke(RestInvocationHandler.java:111)
```
with older java versions one could work around it with a pretty dirty trick: https://stackoverflow.com/questions/25163131/httpurlconnection-invalid-http-method-patch

but with the newer java versions (like ie 22.0.1) the workaround does not work any more

any idea how to bypass the problem?

**Comment by mmazi** [comment]
See also #95, #97, #100.

**Comment by andre77** [comment]
here is an idea 
https://github.com/mmazi/rescu/pull/148

**Comment by mmazi** [comment]
May be solved by using the Apache client.

**Comment by andre77** [comment]
Yes, this issue is solved with the merge https://github.com/mmazi/rescu/commit/c5e8b0f33e27f8afe286be7f4fa71667d1e818a7

**Comment by mmazi** [comment]
@andre77 Please provide short instructions how to use this solution.

**Comment by andre77** [comment]
in order to be able to use @jakarta.ws.rs.PATCH requests
for example see this method: https://www.gate.io/docs/developers/apiv4/#amend-an-order
in the api interface you create the annotation an a method
```
  @PATCH
  @Path("spot/orders/{order_id}")
  SpotOrder updateSpotOrder(...
```

and override the default connection type with "apache"
```
ClientConfig rescuConfig  = ...
rescuConfig.setConnectionType(si.mazi.rescu.clients.HttpConnectionType.apache);
```
or using the config rescu.properties:
```
rescu.http.connectionType=apache       # one of [ java | apache ]. Defaults to java.

```

**Comment by mmazi** [comment]
ExchangeSpecification is not part of rescu (probably part of XChange). With rescu, set this in rescu.properties:

    rescu.http.connectionType=apache
