### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by ntashev** [mmazi/rescu#90]
When the following valid json is passed as input:

``` javascript
{
    "key":[null]
}
```

the following exception is thrown:

``` java
    java.lang.NullPointerException: null
    at si.mazi.rescu.Params.toString(Params.java:181) ~[rescu-1.8.1.jar:na]
    at si.mazi.rescu.Params.iterableToString(Params.java:190) ~[rescu-1.8.1.jar:na]
    at si.mazi.rescu.Params.toString(Params.java:171) ~[rescu-1.8.1.jar:na]
    at si.mazi.rescu.Params.getParamValueAsString(Params.java:164) ~[rescu-1.8.1.jar:na]
    at si.mazi.rescu.Params.asHttpHeaders(Params.java:156) ~[rescu-1.8.1.jar:na]
```

**Comment by mmazi** [comment]
Can you please provide more details -- this json is passed as input to what? Can you provide a full stack trace? Perhaps even create a test case that demonstrates this error? Thanks.

**Comment by ntashev** [comment]
I am using https://github.com/CurrencyCloud/currencycloud-java, which is using this library. The full stack trace is:

``` java
java.lang.NullPointerException: null
at si.mazi.rescu.Params.toString(Params.java:181) ~[rescu-1.8.1.jar:na]
at si.mazi.rescu.Params.iterableToString(Params.java:190) ~[rescu-1.8.1.jar:na]
at si.mazi.rescu.Params.toString(Params.java:171) ~[rescu-1.8.1.jar:na]
at si.mazi.rescu.Params.getParamValueAsString(Params.java:164) ~[rescu-1.8.1.jar:na]
at si.mazi.rescu.Params.asHttpHeaders(Params.java:156) ~[rescu-1.8.1.jar:na]
at com.currencycloud.client.exception.CurrencyCloudException.setInvocation(CurrencyCloudException.java:62) ~[currencycloud-java-0.7.1.jar:na]
at com.currencycloud.client.exception.CurrencyCloudException.<init>(CurrencyCloudException.java:54) ~[currencycloud-java-0.7.1.jar:na]
at com.currencycloud.client.exception.UnexpectedException.<init>(UnexpectedException.java:8) ~[currencycloud-java-0.7.1.jar:na]
at com.currencycloud.client.ExceptionTransformer.aroundInvoke(ExceptionTransformer.java:23) ~[currencycloud-java-0.7.1.jar:na]
at si.mazi.rescu.InterceptedInvocationHandler.invoke(InterceptedInvocationHandler.java:42) ~[rescu-1.8.1.jar:na]
at com.currencycloud.client.Reauthenticator.aroundInvoke(Reauthenticator.java:23) ~[currencycloud-java-0.7.1.jar:na]
at si.mazi.rescu.InterceptedInvocationHandler.invoke(InterceptedInvocationHandler.java:42) ~[rescu-1.8.1.jar:na]
at com.sun.proxy.$Proxy20.createBeneficiary(Unknown Source) ~[na:na]
at com.currencycloud.client.CurrencyCloudClient.createBeneficiary(CurrencyCloudClient.java:283) ~[currencycloud-java-0.7.1.jar:na]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_92]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_92]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_92]
at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_92]
at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:180) ~[cxf-core-3.1.4.jar:3.1.4]
at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96) ~[cxf-core-3.1.4.jar:3.1.4]
at org.apache.cxf.jaxrs.validation.JAXRSBeanValidationInvoker.invoke(JAXRSBeanValidationInvoker.java:51) ~[cxf-rt-frontend-jaxrs-3.1.4.jar:3.1.4]
at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:200) [cxf-rt-frontend-jaxrs-3.1.4.jar:3.1.4]
at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:99) [cxf-rt-frontend-jaxrs-3.1.4.jar:3.1.4]
at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59) [cxf-core-3.1.4.jar:3.1.4]
at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96) [cxf-core-3.1.4.jar:3.1.4]
at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308) [cxf-core-3.1.4.jar:3.1.4]
at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121) [cxf-core-3.1.4.jar:3.1.4]
at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:251) [cxf-rt-transports-http-3.1.4.jar:3.1.4]
at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234) [cxf-rt-transports-http-3.1.4.jar:3.1.4]
at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208) [cxf-rt-transports-http-3.1.4.jar:3.1.4]
at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160) [cxf-rt-transports-http-3.1.4.jar:3.1.4]
at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:180) [cxf-rt-transports-http-3.1.4.jar:3.1.4]
at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:293) [cxf-rt-transports-http-3.1.4.jar:3.1.4]
at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:212) [cxf-rt-transports-http-3.1.4.jar:3.1.4]
at javax.servlet.http.HttpServlet.service(HttpServlet.java:707) [servlet-api-3.1.jar:3.1.0]
at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:268) [cxf-rt-transports-http-3.1.4.jar:3.1.4]
at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:837) [jetty-servlet-9.3.8.v20160314.jar:9.3.8.v20160314]
at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583) [jetty-servlet-9.3.8.v20160314.jar:9.3.8.v20160314]
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) [jetty-server-9.3.8.v20160314.jar:9.3.8.v20160314]
at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548) [jetty-security-9.3.8.v20160314.jar:9.3.8.v20160314]
at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226) [jetty-server-9.3.8.v20160314.jar:9.3.8.v20160314]
at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1160) [jetty-server-9.3.8.v20160314.jar:9.3.8.v20160314]
at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511) [jetty-servlet-9.3.8.v20160314.jar:9.3.8.v20160314]
at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) [jetty-server-9.3.8.v20160314.jar:9.3.8.v20160314]
at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1092) [jetty-server-9.3.8.v20160314.jar:9.3.8.v20160314]
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.3.8.v20160314.jar:9.3.8.v20160314]
at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213) [jetty-server-9.3.8.v20160314.jar:9.3.8.v20160314]
at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:119) [jetty-server-9.3.8.v20160314.jar:9.3.8.v20160314]
at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134) [jetty-server-9.3.8.v20160314.jar:9.3.8.v20160314]
at org.eclipse.jetty.server.Server.handle(Server.java:518) [jetty-server-9.3.8.v20160314.jar:9.3.8.v20160314]
at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308) [jetty-server-9.3.8.v20160314.jar:9.3.8.v20160314]
at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:244) [jetty-server-9.3.8.v20160314.jar:9.3.8.v20160314]
at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273) [jetty-io-9.3.8.v20160314.jar:9.3.8.v20160314]
at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95) [jetty-io-9.3.8.v20160314.jar:9.3.8.v20160314]
at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:186) [jetty-io-9.3.8.v20160314.jar:9.3.8.v20160314]
at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273) [jetty-io-9.3.8.v20160314.jar:9.3.8.v20160314]
at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95) [jetty-io-9.3.8.v20160314.jar:9.3.8.v20160314]
at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93) [jetty-io-9.3.8.v20160314.jar:9.3.8.v20160314]
at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:246) [jetty-util-9.3.8.v20160314.jar:9.3.8.v20160314]
at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:156) [jetty-util-9.3.8.v20160314.jar:9.3.8.v20160314]
at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654) [jetty-util-9.3.8.v20160314.jar:9.3.8.v20160314]
at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572) [jetty-util-9.3.8.v20160314.jar:9.3.8.v20160314]
at java.lang.Thread.run(Thread.java:745) [na:1.8.0_92]
```

**Comment by mmazi** [comment]
Fixed, thanks for reporting.
